dist:
  name: opentelemetry-collector
  description: Opentelemetry collector distribution for instrumenting chs services
  output_path: ./opentelemetry-collector
  debug_compilation: true

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.150.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.150.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter v0.150.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.150.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.150.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.150.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension  v0.150.0
